version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - /home/mzoheir/data/nginx:/etc/nginx
    networks:
      - inception_network

  wordpress:
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - ./envwordpress/tools
    env_file:
      - .env
    
    networks:
      - inception_network

  mariadb:
    build:
      context: ./requirements/mariadb
    environment:
      - dbuser = ${db_user}
      - dbname = ${db_name}
      - dbpw = ${db_pw}
    volumes:
      - /home/mzoheir/data/database:/var/lib/mysql
    networks:
      - inception_network

networks:
  inception_network:
    driver: bridge
