FROM debian:stable

RUN apt-get update -y && \
    apt-get install mariadb-server -y

RUN sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf && \
    sed -i 's|^#user\s*=.*|user = root|' /etc/mysql/mariadb.conf.d/50-server.cnf && \
    sed -i 's|^#datadir\s*=.*|datadir = /var/lib/mysql|' /etc/mysql/mariadb.conf.d/50-server.cnf && \
    sed -i 's|^#tmpdir\s*=.*|tmpdir = /tmp|' /etc/mysql/mariadb.conf.d/50-server.cnf && \
    sed -i 's|^bind-address\s*=.*|bind-address = mariadb|' /etc/mysql/mariadb.conf.d/50-server.cnf

RUN mkdir /run/mysqld

COPY tools/mariadb.sh /mariadb.sh

RUN chmod +x /mariadb.sh

EXPOSE 3306

CMD ["sh","./mariadb.sh"]


