FROM debian:bullseye
RUN apt-get install && apt-get update -y &&  apt-get install -y nginx && apt-get install nano -y
COPY server.crt /etc/ssl/certs/
COPY server.key /etc/ssl/private/
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]

